# This file was generated by GoReleaser. DO NOT EDIT.
cask "suuntool" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "62306e37a875ff562f28d3243e5e40eb8c3939e66db6168bf51197829b570ae4"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8180781fa86daabcd064475dc1c1845a2c07f64e7ee7e3045edaf120f1c7adeb"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6efe5bc59c762c73f2c7e010f8dfa3b14a861880f3148a16e11ed4658a9b38de"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98a152a7a705fa09cd1a73afb857ed1ea44862cda345a86d703a4a049630d35d"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "suuntool"
  desc "Unofficial CLI for the Suunto / Sports-Tracker API"
  homepage "https://github.com/tajchert/suuntool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suuntool"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/suuntool"] if OS.mac?
  end

  # No zap stanza required

end
