# This file was generated by GoReleaser. DO NOT EDIT.
cask "suuntool" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "25d2919b3360be1f4864cf301cf5ab506976550e35d26072b5c3be40fecca060"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca21062f70c17559834d69d8125679377cea9fc4e5e0cdea0a715bbb74716dfd"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e8e77a56b0eac67d725eec6d435968f20e0e88505e811b6145ebec63448e7c0"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c32f479f25078250d436edce75f3196932623cf10d973798841c0bb949cd803b"
      url "https://github.com/tajchert/suuntool/releases/download/v#{version}/suuntool_#{version}_linux_arm64.tar.gz"
    end
  end

  name "suuntool"
  desc "Unofficial CLI for the Suunto / Sports-Tracker API"
  homepage "https://github.com/tajchert/suuntool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "suuntool"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/suuntool"] if OS.mac?
  end

  # No zap stanza required

end
