# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grepmail < Formula
  desc "Fast, grep-style CLI for searching and exploring mbox mail archives"
  homepage "https://github.com/tajchert/grepmail"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tajchert/grepmail/releases/download/v0.2.2/grepmail_0.2.2_darwin_amd64.tar.gz"
      sha256 "2d4ff53908494f5fb9292c52cfff0b6c3e4ed902539ea2ede211e0052368d081"

      define_method(:install) do
        bin.install "grepmail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tajchert/grepmail/releases/download/v0.2.2/grepmail_0.2.2_darwin_arm64.tar.gz"
      sha256 "dd9a20243ff2fdb9d4e3311dcb5ebad83febf5f287ceddd13d34fafcd59aa17d"

      define_method(:install) do
        bin.install "grepmail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tajchert/grepmail/releases/download/v0.2.2/grepmail_0.2.2_linux_amd64.tar.gz"
      sha256 "1740d16465cf1b1b623240c229c99160a763d5be07db655be8331c853604fba3"
      define_method(:install) do
        bin.install "grepmail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tajchert/grepmail/releases/download/v0.2.2/grepmail_0.2.2_linux_arm64.tar.gz"
      sha256 "3c4e315cc52fc2c941e54e9edcf30ee37dcf5d21bcd883c8f93be5c4aaa28ad8"
      define_method(:install) do
        bin.install "grepmail"
      end
    end
  end

  test do
    assert_match "grepmail", shell_output("#{bin}/grepmail version")
  end
end
