# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suuntool < Formula
  desc "Unofficial CLI for the Suunto / Sports-Tracker API"
  homepage "https://github.com/tajchert/suuntool"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tajchert/suuntool/releases/download/v0.7.0/suuntool_0.7.0_darwin_amd64.tar.gz"
      sha256 "ab1a0c0d49da82583061c511c77527d3f5f9518a189ad9fdac33ef41bfae58c3"

      define_method(:install) do
        bin.install "suuntool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tajchert/suuntool/releases/download/v0.7.0/suuntool_0.7.0_darwin_arm64.tar.gz"
      sha256 "310371b617fd364fa0373711a66e7d29c984d735e14c9c26bfa9ab64be2b319f"

      define_method(:install) do
        bin.install "suuntool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tajchert/suuntool/releases/download/v0.7.0/suuntool_0.7.0_linux_amd64.tar.gz"
      sha256 "879d777369d22ec7a9587dca99ea613b2a568ef079e0414d3f01f0461e34ffb2"
      define_method(:install) do
        bin.install "suuntool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tajchert/suuntool/releases/download/v0.7.0/suuntool_0.7.0_linux_arm64.tar.gz"
      sha256 "cc20ac35257757cbd02756cc03b3fac06da744b83372bf107086a4f4ffe9c089"
      define_method(:install) do
        bin.install "suuntool"
      end
    end
  end

  test do
    assert_match "suuntool", shell_output("#{bin}/suuntool version")
  end
end
