# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suuntool < Formula
  desc "Unofficial CLI for the Suunto / Sports-Tracker API"
  homepage "https://github.com/tajchert/suuntool"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tajchert/suuntool/releases/download/v0.9.0/suuntool_0.9.0_darwin_amd64.tar.gz"
      sha256 "8035973b0d187b5b40e0682c674dbf15808288d7a42ad452c51796f0ea576a37"

      define_method(:install) do
        bin.install "suuntool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tajchert/suuntool/releases/download/v0.9.0/suuntool_0.9.0_darwin_arm64.tar.gz"
      sha256 "45b809808c034fb469a8fe543e769ba7d7ba7dd05a559af92cb52c1dba12bf54"

      define_method(:install) do
        bin.install "suuntool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tajchert/suuntool/releases/download/v0.9.0/suuntool_0.9.0_linux_amd64.tar.gz"
      sha256 "4dcef2c860550716f807c58ffd0bef2cf29f0a66e771db69134cc94a24a6cbdc"
      define_method(:install) do
        bin.install "suuntool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tajchert/suuntool/releases/download/v0.9.0/suuntool_0.9.0_linux_arm64.tar.gz"
      sha256 "81eaab438776b08e50b8f75157aa8853b9ad9036f2c91118b466508cdc7c8c13"
      define_method(:install) do
        bin.install "suuntool"
      end
    end
  end

  test do
    assert_match "suuntool", shell_output("#{bin}/suuntool version")
  end
end
